### ISSUE TITLE
Unity rig return error on generation

### ISSUE THREAD

**Issue by BasilYes** [SAM-tak/BlenderGameRig#12]
For recrete issue:
1. generate unity skeleton
![image](https://github.com/SAM-tak/BlenderGameRig/assets/36816595/d3f813a0-e6d1-453d-b195-4740f14fcae5)
2. click button generate 
![image](https://github.com/SAM-tak/BlenderGameRig/assets/36816595/cd557feb-2fcc-44f0-8001-35ef7e5ee4a8)
3. get an error
![image](https://github.com/SAM-tak/BlenderGameRig/assets/36816595/78024af5-5c34-4068-ad10-c1e6c5088835)
(cat return error too)

**Comment by SAM-tak** [comment]
Thank you for reporting the bug.

Fixed it. Try it!

https://github.com/SAM-tak/BlenderGameRig/releases/tag/v1.6.3
