### ISSUE TITLE
Blender 4.2, generated rig shrinks mesh

### ISSUE THREAD

**Issue by gentlecolts** [SAM-tak/BlenderGameRig#13]
When parenting a mesh (automatic weights) to the generated rig in blender 4.2.0, the mesh will shrink.  This appears to be due to the constraints, possibly related to squash/stretch, as parenting to the metarig (for testing) does not produce this effect.  as an example:

Before parent:
![image](https://github.com/user-attachments/assets/6ff58555-774c-43d5-b647-1dd40ff755d5)

After Parent:
![image](https://github.com/user-attachments/assets/8e5214ce-977f-4787-8fdd-ff48509d5098)

**Comment by gentlecolts** [comment]
This seems directly related to the "maintain volume" constraint that gets added, as disabling that seems to remove the issue.  Will update again if I find anything else

**Comment by SAM-tak** [comment]
I cannot confirm the reported issue in my own environment.
Perhaps setting IK Stretch to 0 might resolve it?
If you discover more details about the reproduction method or any workarounds, please let me know.

**Comment by gentlecolts** [comment]
The issue in my case was 100% the shrink mesh constraints, however I'm also unable to reproduce outside of that particular project.  I tried re-creating things in a clean project with a makehuman mesh and did not observe the shrinking that I mention in my original post.  Tempted to declare this as some mysterious issue with that project and just re-create the rig unless I can reproduce

**Comment by gentlecolts** [comment]
I think i figured this one out.  My metarig (and generated rig) were scaled.  After applying scale, the distortion from maintain volume no longer occurs
