### ISSUE TITLE
Pole targets

### ISSUE THREAD

**Issue by rt974** [SAM-tak/BlenderGameRig#2]
Hi,

is there a way to change the damn pole targets such as c.thigh_ik.R to regular ones that you can place in the 3D scene, these stupid arrows always flip in the weirdest direction possible ten times per second to fix that you have to add a million keyframes, this is so stupid. rigify had the same dumb problem lately, like you think its a good improvement it looks good wow these nicest arrows ever, but you actually never used it in practice, animating a character. If only it happened one or two times per day, no its constantly flipping in the wrong direction, also when you try to rotate the damn thing it doesnt go in any logical direction it goes where it pleases and you have to deal with that, even you press R and go in the same direction the arrow decides to go in random directions every single time.

If you can tell me how to dump that arrow thing i can continue using this addon, cause right now my idea is to get rid of it and build a simple ik rig myself using the gamerig base skeleton that has correct bone hierarchy for unity.

thanks for your time.

**Comment by rt974** [comment]
Just look how convenient it is to animate a character with your rig. i believe you dont use it yourself.

https://www.youtube.com/watch?v=bGHus7IPrUQ

`<iframe width="560" height="315" src="https://www.youtube.com/embed/bGHus7IPrUQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`

_I like how the code tag allows to embed youtube videos._

**Comment by rt974** [comment]
I recorded another video to show you how convenient this rig is to use https://youtu.be/1ujm7nUMTjw

As you can see everytime i fix the flappy elbow it creates 2 more flaps left/right, and this goes on forever untill the timeline is full of keyframes. Please tell me my Metarig has incorrect bone rolls or something cause if this is your rig causing this then its time to find another job.

**Comment by rt974** [comment]
And you know what the latest rigify generated rigs also make use of this advanced-retarded concept of IK pole target.

**Comment by rt974** [comment]
if you watch closely when you cross a certain value for one axis, it flaps in another direction, man only this is enough to uninstall this addon and forget it just like the godamned rigify. And now that i think about it i wonder if you even talk english.

**Comment by rt974** [comment]
I just verified, it does exactly the same flapping on a newly spawned metarig, generated rig, didnt change anything to the metarig, and it flaps like crazy when the rotation arrives at a certain value.

**Comment by Tobi-Mob** [comment]
Hi,

If anyone has similar issues with this addon or rigify:
I only rotate the arm and thight IK bones around the Z-Axis.
That works pretty well for me.

![gif1](https://user-images.githubusercontent.com/69400800/89718660-bca37a80-d9c0-11ea-9cf7-c00e82dd7657.gif)
![gif2](https://user-images.githubusercontent.com/69400800/89718662-be6d3e00-d9c0-11ea-9bb8-b1b12d7dbc6a.gif)

**Comment by SAM-tak** [comment]
Thank you, Tobi-Mob!

Yeah, this IK direction controller is bad... but not easy to port new rigify's pole target mechanism...it's too complex.

**Comment by SAM-tak** [comment]
![pole](https://user-images.githubusercontent.com/250165/90978973-95d27000-e58c-11ea-9ddc-5994bfbf7dc3.gif)

I always edit this controller with 'Local transform orientation' and using rotation gizmo or property panel, haven't use 'R' key rotation.
I change Y-axis value mainly, X-axis is optional. then gamerig locked Z-axis.

**Comment by SAM-tak** [comment]
Latest release has IK pole option.
Different way than Rigify, but it's getting a better feel.
