### ISSUE TITLE
Generate Rig error on 2.93

### ISSUE THREAD

**Issue by Hazukiaoi** [SAM-tak/BlenderGameRig#7]
![image](https://user-images.githubusercontent.com/5172646/121025415-b7c57800-c7d7-11eb-8e48-557ac1b19b01.png)
maybe is the bpy.props api update?
https://wiki.blender.org/wiki/Reference/Release_Notes/2.93/Python_API
https://docs.blender.org/api/current/bpy.props.html

Add Property on 2.93 is like this
my_int: bpy.props.IntProperty()

**Comment by SAM-tak** [comment]
Thanks for your bug report!
Fixed it.
