### ISSUE TITLE
When Set FK->IK Error

### ISSUE THREAD

**Issue by Hazukiaoi** [SAM-tak/BlenderGameRig#8]
![image](https://user-images.githubusercontent.com/5172646/123431769-3a35a080-d5fc-11eb-964f-217beed919f6.png)
When i Generate rig wihr game rig, and set Snap FK->IK error say no attribute thigh_fk

**Comment by SAM-tak** [comment]
This problem is going to take a while to solve.

Quick Workaround:
Save file after generate rig and quit blender temporary, and re-open it. it should work.

**Comment by SAM-tak** [comment]
https://devtalk.blender.org/t/typing-get-type-hints-failed-with/19258

It seems to be a bug in Python.
The fix may be in the next version of Blender.（3.0 or 2.93.2 later)

**Comment by SAM-tak** [comment]
i confirmed this issue was solved at Blender 3.0.0 later.
